sudo qemu-system-arm \
-kernel ./kernel-qemu-4.4.34-jessie \
-append "root=/dev/sda2 panic=0 rootfstype=ext4 rw" \
-hda raspbian-stretch.qcow \
-cpu arm1176 -m 256 \
-M versatilepb \
-nodefaults \
-serial stdio \
-net nic -net user \
-net tap,ifname=vnet0,script=no,downscript=no \
-soundhw ac97 \
-usb \
-device usb-ehci,id=ehci \
